### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by satishkrr** [riteshpanjwani/pyiwn#17]
hi when i execute this code 
iwn = pyiwn.IndoWordNet()

im getting this error 
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16: character maps to <undefined>

could you help out pls 

thanks

**Comment by sidhurukku** [comment]
i am also facing the same issue.
Can anyone please help to solve this?

**Comment by ratul2016das** [comment]
The iwn.py file needs to be modified..... I am able to do the modification locally and read the synsets

**Comment by mannprerak2** [comment]
Modify the iwn.py file.
At line 50, do => `f = open(filename, encoding='uf8')`

**Comment by SandipSPatil** [comment]
for the command 
iwn = pyiwn.IndoWordNet()

im getting this error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16: character maps to

could you help out pls

thanks

**Comment by SandipSPatil** [comment]
> The iwn.py file needs to be modified..... I am able to do the modification locally and read the synsets



> The iwn.py file needs to be modified..... I am able to do the modification locally and read the synsets

Sir, How you have resolved this issue locally....please help me for Marathi Language

**Comment by Tawseef-Mir** [comment]
> The iwn.py file needs to be modified..... I am able to do the modification locally and read the synsets

can you please help me how to modify iwn.py as i'm facing the same issue for KASHMIRI language

**Comment by riteshpanjwani** [comment]
Hi, please install the latest version, clone the repo, cd into repo root and run ``` python setup.py install ```
