### ISSUE TITLE
pyiwn import problem

### ISSUE THREAD

**Issue by suman101112** [riteshpanjwani/pyiwn#4]
from pyiwn import pyiwn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/suman_ajit/anaconda/lib/python2.7/site-packages/pyiwn/pyiwn.py", line 1, in <module>
    from pyiwn import utils
ImportError: cannot import name utils

**Comment by riteshpanjwani** [comment]
Hi @suman101112,

I have updated the README and it explicitly mentions that the package works for Python 3.5+ and is to be installed with pip3 if pip defaults to Python 2.7.x.
Sorry for the inconvenience caused.

**Comment by riteshpanjwani** [comment]
I have completely revamped the inner workings of the library and have fixed these issues. I would recommend you to do a full clean reinstall:

pip uninstall pyiwn
pip install --upgrade pyiwn

And follow the steps in this examples notebook: https://github.com/riteshpanjwani/pyiwn/blob/master/examples/example.ipynb

Regards,
Ritesh
