### ISSUE TITLE
IndexError: list index out of range for many languages

### ISSUE THREAD

**Issue by anoopkunchukuttan** [riteshpanjwani/pyiwn#6]
Hi, 

While trying to access indowordnet for some languages, I encounter IndexError. 

Here is an example: 
```python
for lang in ['assamese']: 

        print("===== Language: {}".format(lang))

        # Choose a language and create an object of the IndoWordNet class.
        iwn = pyiwn.IndoWordNet(lang)

        # All Synsets
        syns = iwn.all_synsets()
        syn_count[lang]=len(syns)
```

The following is the error observed: 

```
===== Language: assamese
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-28-bbfe767b3595> in <module>()
      7 
      8         # All Synsets
----> 9         syns = iwn.all_synsets()
     10         syn_count[lang]=len(syns)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyiwn-1.0-py3.6.egg\pyiwn\pyiwn.py in all_synsets(self, pos)
     58             for line in fo:
     59                 sp = utils.clean_line(line)
---> 60                 synset_data = utils.synset_data(sp, pos)
     61                 synset_id, head_word, lemma_names, pos, gloss, examples = synset_data[0], synset_data[1], synset_data[2], synset_data[3], synset_data[4], synset_data[5]
     62                 synsets.append(Synset(synset_id, head_word, lemma_names, pos, gloss, examples))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyiwn-1.0-py3.6.egg\pyiwn\utils.py in synset_data(data, pos)
     19         gloss_examples_sp = data[2].split(':')
     20         gloss = gloss_examples_sp[0]
---> 21         examples = re.sub('"', '', gloss_examples_sp[1]).split(' / ')
     22     else:
     23         gloss, examples = '', []

IndexError: list index out of range
```

I found this error while trying to access all words in some languages also.

**Comment by anoopkunchukuttan** [comment]
iwn.all_synsets() raises this exception for the following languages: 
assamese, bodo, gujarati, kannada, kashmiri, malayalam, oriya, punjabi, telugu

iwn.all_words() raises this exception for the following languages: 
kashmiri, marathi, nepali, punjabi, sanskrit, tamil

**Comment by suman101112** [comment]
for all_synsets() index out of range exception, sir, please check the data files in pyiwn_data. Some parsed files have unnecessary tabs. I had the same problem with Telugu data. I just modified the data files and removed unnecessary tabs

**Comment by ranjansarma** [comment]
For assamese the file pyiwn_data/synsets/all.assamese has unnecessary tabs in lines with synset id 5144,12021,17105.
Removing it works for me.

**Comment by riteshpanjwani** [comment]
Hi All,

I have completely revamped the inner workings of the library and have fixed these issues. I would recommend you to do a full clean reinstall:

pip uninstall pyiwn
pip install --upgrade pyiwn

And follow the steps in this examples notebook: https://github.com/riteshpanjwani/pyiwn/blob/master/examples/example.ipynb

Regards,
Ritesh
