### ISSUE TITLE
IndexError: list index out of range while obtaining telugu synsets.

### ISSUE THREAD

**Issue by suman101112** [riteshpanjwani/pyiwn#7]
```
from pyiwn import pyiwn
iwn = pyiwn.IndoWordNet('telugu')
print(iwn.synsets('జ్వరం'),pos=pyiwn.NOUN)
```
Traceback (most recent call last):
    print(iwn.synsets('జ్వరం'),pos=pyiwn.NOUN)
    synset_data = utils.synset_data(sp, pos)
    examples = re.sub('"', '', gloss_examples_sp[1]).split(' / ')
IndexError: list index out of range

**Comment by suman101112** [comment]
the problem is in parsed files of all.telugu and noun.telugu, The line is unable to split at ":", so we are getting index out of range exception. Just modified the files and deleted extra unnecessary tabs.

**Comment by riteshpanjwani** [comment]
I have completely revamped the inner workings of the library and have fixed these issues. I would recommend you to do a full clean reinstall:

pip uninstall pyiwn
pip install --upgrade pyiwn

And follow the steps in this examples notebook: https://github.com/riteshpanjwani/pyiwn/blob/master/examples/example.ipynb

Regards,
Ritesh
