### ISSUE TITLE
ImportError: cannot import name 'pyiwn'

### ISSUE THREAD

**Issue by tarangn20** [riteshpanjwani/pyiwn#8]
I am using python version 3.6.4.. and still facing this issue..
thank you.

**Comment by riteshpanjwani** [comment]
I have completely revamped the inner workings of the library and have fixed these issues. I would recommend you to do a full clean reinstall:

pip uninstall pyiwn
pip install --upgrade pyiwn

And follow the steps in this examples notebook: https://github.com/riteshpanjwani/pyiwn/blob/master/examples/example.ipynb

Regards,
Ritesh
